name = "hyp-convert"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "hyp_convert_db"
database_name = "hyp-convert-db"
database_id = "cac71aa5-8a30-4a22-adaf-5db1da6b4400"
