/**
 * Presentation Converter Module
 * Handles:
 *  - Text → PPTX (using PptxGenJS)
 *  - PPTX → Text (using JSZip to extract text from slide XML)
 *  - Markdown → PPTX (parse headings as slide titles)
 */

import PptxGenJS from 'pptxgenjs';
import JSZip from 'jszip';
import * as FileUtils from './fileUtils';
import { Platform } from 'react-native';

// =========================================
// CREATION: Text → PPTX
// =========================================

/**
 * Convert Text to PPTX (Smart Slide Generation)
 * Splits text on double newlines for slides, first line of each section = title
 */
export const textToPPTX = async (text: string, title: string = 'Presentation'): Promise<{ uri?: string; success: boolean; error?: string }> => {
    try {
        const pptx = new PptxGenJS();
        pptx.layout = 'LAYOUT_16x9';

        // Title Slide with gradient background
        const slide1 = pptx.addSlide();
        slide1.background = { color: '1a1a2e' };
        slide1.addText(title, {
            x: 0.5, y: 2, w: '90%', h: 1.5,
            fontSize: 40, align: 'center', color: 'FFFFFF',
            fontFace: 'Arial',
            bold: true,
        });
        slide1.addText('Generated by HYP Convert', {
            x: 0.5, y: 4.5, w: '90%', h: 0.5,
            fontSize: 14, align: 'center', color: '888888',
            fontFace: 'Arial',
        });

        // Content Slides (split by double newline)
        const sections = text.split('\n\n').filter(s => s.trim());

        for (let i = 0; i < sections.length; i++) {
            const section = sections[i];
            const lines = section.split('\n');
            const header = lines[0].replace(/^#+\s*/, ''); // Strip markdown headers
            const body = lines.slice(1).join('\n').trim();

            const slide = pptx.addSlide();
            slide.background = { color: 'FFFFFF' };

            // Slide number
            slide.addText(`${i + 1}`, {
                x: 9.0, y: 5.0, w: 0.5, h: 0.3,
                fontSize: 10, color: 'AAAAAA', align: 'right',
            });

            // Header with accent line
            slide.addText(header.substring(0, 120), {
                x: 0.5, y: 0.3, w: '90%', h: 0.8,
                fontSize: 28, bold: true, color: '1a1a2e',
                fontFace: 'Arial',
            });

            // Accent line
            slide.addShape(pptx.ShapeType.rect, {
                x: 0.5, y: 1.15, w: 1.5, h: 0.04,
                fill: { color: '4361ee' },
            });

            if (body) {
                // Format bullet points
                const bodyLines = body.split('\n');
                const formattedBody = bodyLines.map(line => {
                    const trimmed = line.trim();
                    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
                        return '  •  ' + trimmed.substring(2);
                    }
                    if (/^\d+\.\s/.test(trimmed)) {
                        return '  ' + trimmed;
                    }
                    return trimmed;
                }).join('\n');

                slide.addText(formattedBody, {
                    x: 0.5, y: 1.4, w: '90%', h: 3.8,
                    fontSize: 18, color: '444444',
                    fontFace: 'Arial',
                    valign: 'top',
                    lineSpacingMultiple: 1.3,
                    paraSpaceAfter: 6,
                });
            }
        }

        // Save
        const base64 = await pptx.write({ outputType: 'base64' }) as string;
        const uri = await FileUtils.writeAsStringAsync(
            `${FileUtils.getCacheDirectory()}converted.pptx`,
            base64,
            { encoding: 'base64' }
        );

        return { uri, success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : 'Gagal membuat PPTX' };
    }
};

// =========================================
// EXTRACTION: PPTX → Text
// =========================================

/**
 * Extract meaningful text from PPTX
 * Parses slide XML to find <a:t> text elements in correct order
 */
export const pptxToText = async (uri: string): Promise<{ content?: string; success: boolean; error?: string }> => {
    try {
        // Load ZIP
        let zipData: any;
        if (Platform.OS === 'web') {
            const response = await fetch(uri);
            zipData = await response.arrayBuffer();
        } else {
            zipData = await FileUtils.readAsBase64Async(uri);
        }

        const loadOptions = Platform.OS === 'web' ? {} : { base64: true };
        const zip = await JSZip.loadAsync(zipData, loadOptions);

        // Find all slide files (ppt/slides/slide1.xml, slide2.xml, etc.)
        const slideFiles = Object.keys(zip.files)
            .filter(f => /^ppt\/slides\/slide\d+\.xml$/i.test(f))
            .sort((a, b) => {
                const numA = parseInt(a.match(/slide(\d+)/)?.[1] || '0');
                const numB = parseInt(b.match(/slide(\d+)/)?.[1] || '0');
                return numA - numB;
            });

        if (slideFiles.length === 0) {
            return { success: false, error: 'Tidak ada slide ditemukan di file PPTX' };
        }

        let fullText = '';

        for (let i = 0; i < slideFiles.length; i++) {
            const slideFile = zip.file(slideFiles[i]);
            if (!slideFile) continue;

            const xmlContent = await slideFile.async('string');

            // Extract all <a:t> text elements (PowerPoint text tags)
            const textElements: string[] = [];
            const textRegex = /<a:t>([^<]*)<\/a:t>/g;
            let match;
            while ((match = textRegex.exec(xmlContent)) !== null) {
                if (match[1].trim()) {
                    textElements.push(match[1]);
                }
            }

            if (textElements.length > 0) {
                fullText += `\n--- Slide ${i + 1} ---\n`;

                // Group text elements - detect paragraph breaks from <a:p> tags
                const paragraphTexts: string[] = [];
                let currentParagraph = '';
                const paragraphRegex = /<a:p>([\s\S]*?)<\/a:p>/g;
                let pMatch;

                while ((pMatch = paragraphRegex.exec(xmlContent)) !== null) {
                    const paragraphXml = pMatch[1];
                    const innerTexts: string[] = [];
                    const innerTextRegex = /<a:t>([^<]*)<\/a:t>/g;
                    let tMatch;
                    while ((tMatch = innerTextRegex.exec(paragraphXml)) !== null) {
                        innerTexts.push(tMatch[1]);
                    }
                    if (innerTexts.length > 0) {
                        paragraphTexts.push(innerTexts.join(''));
                    }
                }

                if (paragraphTexts.length > 0) {
                    fullText += paragraphTexts.join('\n') + '\n';
                } else {
                    fullText += textElements.join(' ') + '\n';
                }
            }
        }

        if (!fullText.trim()) {
            return { success: true, content: '[Presentasi ini tidak mengandung teks yang dapat diekstrak.]' };
        }

        return { content: fullText.trim(), success: true };
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : 'Gagal membaca PPTX' };
    }
};

// =========================================
// MARKDOWN → PPTX
// =========================================

/**
 * Convert Markdown to PPTX
 * Uses # headings as slide breaks
 */
export const markdownToPPTX = async (markdown: string, title: string = 'Presentation'): Promise<{ uri?: string; success: boolean; error?: string }> => {
    try {
        // Split markdown on headings to create slides
        const slides: { heading: string; content: string }[] = [];
        const lines = markdown.split('\n');
        let currentHeading = title;
        let currentContent: string[] = [];

        for (const line of lines) {
            const headingMatch = line.match(/^(#{1,3})\s+(.+)/);
            if (headingMatch) {
                // Save previous slide
                if (currentContent.length > 0 || slides.length === 0) {
                    slides.push({ heading: currentHeading, content: currentContent.join('\n') });
                }
                currentHeading = headingMatch[2];
                currentContent = [];
            } else {
                currentContent.push(line);
            }
        }

        // Don't forget the last slide
        if (currentContent.length > 0) {
            slides.push({ heading: currentHeading, content: currentContent.join('\n') });
        }

        // Build text for the generic textToPPTX
        const text = slides.map(s => `${s.heading}\n${s.content}`).join('\n\n');

        return await textToPPTX(text, title);
    } catch (error) {
        return { success: false, error: error instanceof Error ? error.message : 'Gagal mengkonversi Markdown ke PPTX' };
    }
};
